Design
chhoumann/p7 pull request #84
Opened 2022-11-24 13:29 UTC by Ivikhostrup

# What was implemented
Added a design sections

# Explanation
Added the three wireframes and an explanation as to how they solve use cases

# Outcome
A remastering of the classic record: "All Night Long" by Lionel Richie.

2022-11-24 19:33 UTC, chhoumann commented
Looks like this has some conflicts with the main branch. 

Also, some of the images are conflicting with existing ones. E.g. the architecture image says `Code Runner`, which the previous architecture PR correctly stated to be `Test Runner`.

2022-11-25 08:22 UTC, Ivikhostrup commented
@chhoumann The merge conflict has been resolved and the correct image for the architecture section has been added. Just had to recompile after merging master into the design branch.

2022-11-25 09:58 UTC, chhoumann requested changes
Great job, guys. I have some small comments that I hope you can take a look at.

2022-11-25 09:58 UTC, chhoumann commented on report/sections/Chapter 04 - Design/design.tex
> +Based on our specification we have created a design for the application's user interface (UI). The UI had to support the use cases specified in section \ref*{sec:use_cases}, although not all features
```suggestion
Based on our specification we created a design for the application's user interface (UI). The UI had to support the use cases specified in section \ref*{sec:use_cases}, although not all features required in the use cases were included in the design. The goal of the design was to include the features listed as \textit{Must have} and \textit{Should have} in the MoSCoW analysis, but still take the other features into account. This was done to ensure that the most important aspects of the use cases would be satisfied in the design, while also having designed for some of the desirable, but less important features.
```
Past tense & some clarifications. Please do say if you don't agree.

2022-11-25 09:58 UTC, chhoumann commented on report/sections/Chapter 04 - Design/design.tex
> +As mentioned previously not all the use cases have been designed for, because the remaining use cases and related features were deemed as nonessential for a minimal viable product. The next chapter w
I just noticed that the MVP section isn't actually included in our report so far. That is, `MVP.tex` isn't included. That makes this the first place we mention a minimal viable product. Not sure if that's great for the reader---they won't know what that is.

2022-11-25 11:23 UTC, chhoumann approved these changes

2022-11-25 11:23 UTC, merged